mise en place de class plus fragment header dans gift-create
WildCodeSchool/nantes-java-0320-pjt2-makemehappy pull request #35
Opened 2020-04-22 20:02 UTC by swann44

2020-04-22 20:26 UTC, AnnCa44 requested changes

2020-04-22 20:26 UTC, AnnCa44 commented on src/main/resources/static/css/style.css
> +/*.gift-create-form form div input {
commentaire à enlever ligne 241 à 243

2020-04-22 21:06 UTC, AnnCa44 approved these changes

2020-04-23 07:12 UTC, bastienapp approved these changes

2020-04-23 07:18 UTC, merged