added setter and getter and I created a GiftList class
WildCodeSchool/nantes-java-0320-pjt2-makemehappy pull request #6
Opened 2020-04-15 15:29 UTC by Alanrl22

2020-04-15 15:39 UTC, ganout reviewed
Attention tu as modifié et push un fichier que tu n'avais pas à faire (évite de faire git add .), et il y a un problème d'indentation sur le fichier GiftList.java un espace après les parenthèses lignes 12, 15, 21, 29, 37 et supprimer l'espace ligne 44.

2020-04-15 15:58 UTC, ganout approved these changes

2020-04-15 16:11 UTC, bastienapp requested changes

2020-04-15 16:11 UTC, bastienwcs commented on src/main/java/com/wildcodeschool/makemehappy/MakeMeHappyApplication.java
> +
Retours à la ligne inutiles

2020-04-15 16:11 UTC, bastienwcs commented on src/main/java/model/GiftList.java
> +    }
Accolade inutile

2020-04-15 16:11 UTC, bastienwcs commented on src/main/java/model/GiftList.java
> +    public GiftList (String title, String description, Date date) {
Pas d'espace après le nom des méthodes et constructeur (à corriger partout). Tu peux utiliser CTRL + MAJ + ALT + L puis cocher "Rearange code" puis ok

2020-04-15 16:11 UTC, bastienwcs commented on src/main/java/model/GiftList.java
> +        this.date= date;
manque un espace avant le =

2020-04-15 16:11 UTC, bastienwcs commented on src/main/java/model/GiftList.java
> +    private String title;
un retour à la ligne après les blocs (accolades)

2020-04-16 08:25 UTC, bastienapp approved these changes

2020-04-16 08:26 UTC, ganout approved these changes

2020-04-16 08:27 UTC, merged